services:
  - type: web
    name: realstate_backend
    env: python
    plan: free
    # rootDir must point to folder containing manage.py
    rootDir: realstate_backend
    buildCommand: pip install -r requirements.txt
    startCommand: bash -lc "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn realestate_backend.wsgi:application --bind 0.0.0.0:$PORT"